name: Node.js Package

on:
  push:
    branches:
      - master
      - release/*

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Patch version
        run: npm version patch
      - name: Commit changes
        run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Actions"
        git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@wazbat'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
